package ponyvet.gui.articulo;

import java.awt.Color;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ponyvet.config.ConfiguracionesGenerales;
import ponyvet.controller.articulo.ArticuloController;
import ponyvet.modelo.entidades.articulo.Articulo;
import ponyvet.modelo.entidades.articulo.Lote;
import ponyvet.utilities.Validar;

public class JDAjustarCantidad extends javax.swing.JDialog {

    private Articulo articulo;

    public JDAjustarCantidad(java.awt.Frame parent, boolean modal, Articulo articulo) {
        super(parent, modal);
        this.articulo = articulo;
        initComponents();

        txtCantidad.setText(String.valueOf(articulo.getExistencia()));
    }

    private void ajustarExistencia(Float existencia) {

        if (articulo.isLote()) {
            float count = 0.0f;
            Set<Lote> lotes = articulo.getLotes();
            for (Lote lote : lotes) {
                count = count + lote.getExisActual();
            }
            if (existencia >= count) {
                if (existencia > 0 && existencia < ConfiguracionesGenerales.MAXIMA_CANTIDAD_EXISTENCIA) {
                    this.dispose();
                    articulo.setExistencia(existencia);
                    JDLotes jdlotes = new JDLotes(new JFrame(), true, articulo);
                    jdlotes.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null,
                            "La existencia debe ser mayor a 0 y menor a " + ConfiguracionesGenerales.MAXIMA_CANTIDAD_EXISTENCIA,
                            "Cantidad inválida", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null,
                        "Debes agregar una cantiadad mayor al número de lotes existentes\n",
                        "Cantidad inválida", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (existencia >= 0 && existencia < ConfiguracionesGenerales.MAXIMA_CANTIDAD_EXISTENCIA) {
                this.dispose();
                ArticuloController.ajustarExistencia(articulo.getClave(), existencia);
                JFArticulo.actualizarTablaArticulos("");
            } else {
                JOptionPane.showMessageDialog(null,
                        "La existencia debe ser mayor o igual a 0 y menor a " + ConfiguracionesGenerales.MAXIMA_CANTIDAD_EXISTENCIA,
                        "Cantidad inválida", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajustar Cantidad");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Existencia Actual:");

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidad.setText("0.0");
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-checked-22.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtCantidad)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 295, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (Validar.isFloat(txtCantidad.getText())) {
            Float cantidad = Float.parseFloat(txtCantidad.getText());

            if (articulo.isGranel()) { //Se vende a fracciones
                ajustarExistencia(cantidad);
            } else { //No se vende en fracciones
                if (cantidad == Math.round(cantidad)) { //verificar que se una entrada entera
                    ajustarExistencia(cantidad);
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Este producto no se puede vender a granel(fracciones).\n"
                            + "Puedes configurarlo en la pestaña 'Adicional'.",
                            "Granel desactivado", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Cadena no válida. Debes introducir un número positivo entero o decimal",
                    "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
