/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ponyvet.gui.articulo;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ponyvet.controller.articulo.UnidadController;
import static ponyvet.gui.articulo.JDFormularioArticulo.verificarIgualdadUnidad;
import ponyvet.modelo.entidades.articulo.Unidad;

/**
 *
 * @author vladi
 */
public class JDUnidad extends javax.swing.JDialog {
    
    private static final UnidadController controller = new UnidadController();
    private boolean iscompra;
    /**
     * Creates new form JDUnidad
     */
    public JDUnidad(java.awt.Frame parent, boolean modal, boolean iscompra) {
        super(parent, modal);
        initComponents();
        this.iscompra = iscompra;
        JDUnidad.updateTableByNombre("");
        
        tableUnidades.getTableHeader().setBackground(new java.awt.Color(51, 51, 51));
        tableUnidades.getTableHeader().setForeground(java.awt.Color.WHITE);
    }
    
    public static void updateTableByNombre(String keywords){
        tableUnidades.setModel(controller.modelFindByNombre(keywords));
    }
    
    public static void updateTableById(int id){
        tableUnidades.setModel(controller.modelFindById(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUnidades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione el tipo de unidad");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Buscar:");

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-check-all-22.png"))); // NOI18N
        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setText("Crear nueva");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tableUnidades.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tableUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "PZ"},
                {"2", "CAJA"}
            },
            new String [] {
                "Clave", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUnidades.setRowHeight(25);
        tableUnidades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableUnidades.setShowHorizontalLines(true);
        tableUnidades.setShowVerticalLines(true);
        tableUnidades.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableUnidades);
        if (tableUnidades.getColumnModel().getColumnCount() > 0) {
            tableUnidades.getColumnModel().getColumn(0).setMinWidth(50);
            tableUnidades.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableUnidades.getColumnModel().getColumn(1).setMinWidth(350);
            tableUnidades.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tableUnidades.getSelectedRowCount() > 0){            
            int row = tableUnidades.getSelectedRow();
            int uni_id = Integer.valueOf(String.valueOf(tableUnidades.getValueAt(row, 0)));
            
            Unidad unidad = controller.findById(uni_id);
            
            this.dispose();
            
            if(iscompra){
                JDFormularioArticulo.actualizarUnidadCompra(unidad);
                JDFormularioArticulo.actualizarUnidadSalida(unidad);
            }else{
                JDFormularioArticulo.actualizarUnidadSalida(unidad);
            }
            
            if(!verificarIgualdadUnidad()){
                JDFormularioArticulo.txtFactor.setEditable(true);
            }else{
                JDFormularioArticulo.txtFactor.setText("1.0");
                JDFormularioArticulo.calularPrecioSalida();
                JDFormularioArticulo.txtFactor.setEditable(false);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una unidad de la tabla", "Unidad no seleccionada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        JDUnidad.updateTableByNombre(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JDAgregarUnidad addUnidad = new JDAgregarUnidad(new JFrame(), true);
        addUnidad.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tableUnidades;
    private static javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
