package ponyvet.gui.articulo;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ponyvet.controller.articulo.ArticuloController;
import ponyvet.gui.utilities.JInternalFrameCustom;
import ponyvet.modelo.entidades.articulo.Articulo;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

public class JFArticulo extends JInternalFrameCustom {
    
    public JFArticulo() {
        initComponents();
        actualizarTablaArticulos("");
    }
    
    public static void actualizarTablaArticulos(String keywords){
        DefaultTableModel modelo_actual = (DefaultTableModel) tableArticulos.getModel();
        tableArticulos.setModel(ArticuloController.getModelArticulos(
                                modelo_actual, 
                                keywords));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExistencia = new javax.swing.JButton();
        btnLotes = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableArticulos = new ponyvet.gui.utilities.JTableCustom();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Inventario General");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 64));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnAgregar.setBackground(new Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-add-24.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setFocusPainted(false);
        btnAgregar.setFocusable(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 1);
        jPanel2.add(btnAgregar, gridBagConstraints);

        btnEditar.setBackground(new Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-edit-24.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusPainted(false);
        btnEditar.setFocusable(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(btnEditar, gridBagConstraints);

        btnExistencia.setBackground(new Color(255, 255, 255));
        btnExistencia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-adjust-24.png"))); // NOI18N
        btnExistencia.setText("Ajustar existencia");
        btnExistencia.setFocusPainted(false);
        btnExistencia.setFocusable(false);
        btnExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(btnExistencia, gridBagConstraints);

        btnLotes.setBackground(new Color(255, 255, 255));
        btnLotes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-brochure-24.png"))); // NOI18N
        btnLotes.setText("Lotes");
        btnLotes.setFocusPainted(false);
        btnLotes.setFocusable(false);
        btnLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLotesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(btnLotes, gridBagConstraints);

        btnEliminar.setBackground(new Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-trash-can-24.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(btnEliminar, gridBagConstraints);

        btnMostrarTodo.setBackground(new Color(255, 255, 255));
        btnMostrarTodo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMostrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-select-all-24.png"))); // NOI18N
        btnMostrarTodo.setText("Actualizar tabla");
        btnMostrarTodo.setFocusPainted(false);
        btnMostrarTodo.setFocusable(false);
        btnMostrarTodo.setOpaque(true);
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 0);
        jPanel2.add(btnMostrarTodo, gridBagConstraints);

        tableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Descripción", "Existencia", "Precio Com", "Precio Sal", "L", "G", "Categoria", "Min", "Max"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableArticulos.setFocusable(false);
        tableArticulos.setShowHorizontalLines(true);
        tableArticulos.setShowVerticalLines(true);
        tableArticulos.getTableHeader().setReorderingAllowed(false);
        tableArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableArticulosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableArticulos);
        if (tableArticulos.getColumnModel().getColumnCount() > 0) {
            tableArticulos.getColumnModel().getColumn(0).setMinWidth(60);
            tableArticulos.getColumnModel().getColumn(0).setPreferredWidth(150);
            tableArticulos.getColumnModel().getColumn(0).setMaxWidth(150);
            tableArticulos.getColumnModel().getColumn(2).setMinWidth(60);
            tableArticulos.getColumnModel().getColumn(2).setPreferredWidth(120);
            tableArticulos.getColumnModel().getColumn(2).setMaxWidth(120);
            tableArticulos.getColumnModel().getColumn(3).setMinWidth(60);
            tableArticulos.getColumnModel().getColumn(3).setPreferredWidth(150);
            tableArticulos.getColumnModel().getColumn(3).setMaxWidth(150);
            tableArticulos.getColumnModel().getColumn(4).setMinWidth(60);
            tableArticulos.getColumnModel().getColumn(4).setPreferredWidth(150);
            tableArticulos.getColumnModel().getColumn(4).setMaxWidth(150);
            tableArticulos.getColumnModel().getColumn(5).setMinWidth(20);
            tableArticulos.getColumnModel().getColumn(5).setPreferredWidth(20);
            tableArticulos.getColumnModel().getColumn(5).setMaxWidth(20);
            tableArticulos.getColumnModel().getColumn(6).setMinWidth(20);
            tableArticulos.getColumnModel().getColumn(6).setPreferredWidth(20);
            tableArticulos.getColumnModel().getColumn(6).setMaxWidth(20);
            tableArticulos.getColumnModel().getColumn(7).setMinWidth(60);
            tableArticulos.getColumnModel().getColumn(7).setPreferredWidth(200);
            tableArticulos.getColumnModel().getColumn(7).setMaxWidth(200);
            tableArticulos.getColumnModel().getColumn(8).setMinWidth(30);
            tableArticulos.getColumnModel().getColumn(8).setPreferredWidth(50);
            tableArticulos.getColumnModel().getColumn(8).setMaxWidth(50);
            tableArticulos.getColumnModel().getColumn(9).setMinWidth(30);
            tableArticulos.getColumnModel().getColumn(9).setPreferredWidth(50);
            tableArticulos.getColumnModel().getColumn(9).setMaxWidth(50);
        }

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Buscar:");
        jLabel1.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel4.add(jLabel1, gridBagConstraints);

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel4.add(txtBuscar, gridBagConstraints);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-search-22.png"))); // NOI18N
        btnBuscar.setText("Buscar(Enter)");
        btnBuscar.setFocusable(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel4.add(btnBuscar, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Administración del inventario general");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-box-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        JDFormularioArticulo formulario = new JDFormularioArticulo(new JFrame(), true, null);
        formulario.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if(tableArticulos.getSelectedRowCount() > 0){
            int row = tableArticulos.getSelectedRow();
            String clave = (String) tableArticulos.getValueAt(row, 0);
            Articulo art = new ArticuloController().findByClave(clave);
            JDFormularioArticulo editForm = new JDFormularioArticulo(null, true, art);
            editForm.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un artículo de la tabla", "Artículo no seleccionado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (tableArticulos.getSelectedRowCount() > 0) {
            int resp = JOptionPane.showConfirmDialog(null, "¿Deseas borrar el registro?", "Eliminar registro", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if (resp == 0) {
                int row = tableArticulos.getSelectedRow();
                String clave = (String) tableArticulos.getValueAt(row, 0);
                Articulo art = new ArticuloController().findByClave(clave);

                ArticuloController.delete(art);

                

                JFArticulo.actualizarTablaArticulos("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un artículo de la tabla", "Artículo no seleccionado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistenciaActionPerformed
        // TODO add your handling code here:
        
        if (tableArticulos.getSelectedRowCount() > 0) {
            
            int row = tableArticulos.getSelectedRow();
            String clave = (String) tableArticulos.getValueAt(row, 0);
            Articulo art = new ArticuloController().findByClave(clave);
            
            JDAjustarCantidad ajuste = new JDAjustarCantidad(new JFrame(), true, art);
            ajuste.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un artículo de la tabla", "Artículo no seleccionado", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnExistenciaActionPerformed

    private void btnLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLotesActionPerformed
        // TODO add your handling code here:
         if (tableArticulos.getSelectedRowCount() > 0) {        
             int row = tableArticulos.getSelectedRow();
             String clave = (String) tableArticulos.getValueAt(row, 0);
             Articulo art = new ArticuloController().findByClave(clave);
             
             if(art.isLote()){
                 JDVerLotes lotes = new JDVerLotes(new JFrame(), true, clave);
                 lotes.setVisible(true);
             }else{
                 JOptionPane.showMessageDialog(null, "El artículo seleccionado no tiene lotes relacionados", "Artículo sin lotes", JOptionPane.INFORMATION_MESSAGE);
             }
            
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un artículo de la tabla", "Artículo no seleccionado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLotesActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        txtBuscar.setText("");
        JFArticulo.actualizarTablaArticulos("");
        JOptionPane.showMessageDialog(null, "La tabla de artículos se actualizó correctamente.");
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (!txtBuscar.getText().equals("")) {
            String keywords = txtBuscar.getText();
            actualizarTablaArticulos(keywords);
            if (tableArticulos.getRowCount() <= 0) {
                JOptionPane.showMessageDialog(null, "No se encontraron resultados de \"" + txtBuscar.getText() + "\".");
                actualizarTablaArticulos("");
            }else{
                if(ArticuloController.findByClave(keywords) != null){
                    txtBuscar.setText("");
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Debes escribir la clave del artículo o el nombre en el cuadro de busqueda");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyPressed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtBuscar.getText().equals("")) {
                String keywords = txtBuscar.getText();
                actualizarTablaArticulos(keywords);
                if (tableArticulos.getRowCount() <= 0) {
                    JOptionPane.showMessageDialog(null, "No se encontraron resultados de \"" + txtBuscar.getText() + "\".");
                    actualizarTablaArticulos("");
                } else {
                    if (ArticuloController.findByClave(keywords) != null) {
                        txtBuscar.setText("");
                    }
                }
            }
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void tableArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableArticulosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && tableArticulos.getSelectedRowCount() > 0) {
            Point point = evt.getPoint();
            int row = tableArticulos.rowAtPoint(point);
            String clave = (String) tableArticulos.getValueAt(row, 0);
            Articulo art = new ArticuloController().findByClave(clave);
            JDFormularioArticulo editForm = new JDFormularioArticulo(null, true, art);
            editForm.setVisible(true);
            
        }
    }//GEN-LAST:event_tableArticulosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExistencia;
    private javax.swing.JButton btnLotes;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static ponyvet.gui.utilities.JTableCustom tableArticulos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
